jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-def:
        BUILD: stack
        STACK_YAML: stack.yaml
  steps:
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      mkdir -p ~/.local/bin
      curl -skL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin;
    displayName: Install Stack

  - script: |
      brew update && brew install postgres
    displayName: Install Postgres

  - script: |
      export PATH=$HOME/.local/bin:$PATH
      stack --no-terminal --install-ghc test --only-dependencies
    displayName: Build Dependencies

  - script: |
      stack test
    displayName: Test ${{parameters.os}} Package

